name: fitness_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for your app
version: 1.0.0+1

# Environment setup for SDK
environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependencies section (to add packages required for your app)
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8  # Cupertino Icons package
  
  # Image Handling
  image_picker: ^0.8.5+3  # Add the correct version you need
  
  # Firebase Services
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.2

  # Payment
  razorpay_flutter: ^1.3.7

  # Networking
  http: ^1.3.0

  # File Management
  file_picker: ^9.0.2  # Use the latest version
  shared_preferences: ^2.5.2

  # Date Formatting (Added intl package)
  intl: ^0.18.1
  
  # Webview
  webview_flutter: ^4.10.0
  
  # State Management
  flutter_bloc: ^9.1.0
  
  # Camera
  camera: ^0.11.1
  
  # Machine Learning Kit
  google_ml_kit: ^0.19.0
  google_mlkit_commons: ^0.9.0
  
  # File System Paths
  path: ^1.9.1
  path_provider: ^2.1.5
  
  # Cloudinary Integration
  cloudinary_flutter: ^1.3.0
  cloudinary: ^1.2.0
  
  # Charts
  fl_chart: ^0.64.0

  # PDF Generation & Printing
  pdf: ^3.10.4
  printing: ^5.12.0
  
  # PDF Generation and File Opening
  open_file: ^3.5.6
  permission_handler: ^11.3.1

# Dev dependencies (for testing and linting)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Ensuring Material Icons are available in your app
  uses-material-design: true

  # You can add assets here if you need images or other resources
  # assets:
  #   - images/fitn.jpg
  #   - images/a_dot_ham.jpeg
