name: fitness_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for your app
version: 1.0.0+1

# Environment setup for SDK
environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependencies section (to add packages required for your app)
dependencies:
  flutter:
    sdk: flutter

  # Adding the image_picker package for profile picture functionality
  image_picker: ^0.8.5+3  # Add the correct version you need
  cupertino_icons: ^1.0.8  # Cupertino Icons package


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  razorpay_flutter: ^1.3.7
  http: ^1.3.0
  firebase_storage: ^12.4.2


# Dev dependencies (for testing and linting)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Ensuring Material Icons are available in your app
  uses-material-design: true

  # You can add assets here if you need images or other resources
  # assets:
  #  - images/fitn.jpg
  #   - images/a_dot_ham.jpeg

  # You can also add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
