name: fitness_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for your app
version: 1.0.0+1

# Environment setup for SDK
environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependencies section (to add packages required for your app)
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8  # Cupertino Icons package

  # Image Handling
  image_picker: ^0.8.5+3  # Add the correct version you need

  # Firebase Services
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.2

  # Payment
  razorpay_flutter: ^1.3.7

  # Networking
  http: ^1.3.0

  # File Management
  file_picker: ^6.1.1  # Use the latest version

# Dev dependencies (for testing and linting)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Ensuring Material Icons are available in your app
  uses-material-design: true

  # You can add assets here if you need images or other resources
  # assets:
  #  - images/fitn.jpg
  #  - images/a_dot_ham.jpeg
